### ISSUE TITLE
Cannot evaluate FacetNormal() on a parameterized boundary

### ISSUE THREAD

**Issue by minhtriet95** [RBniCS/RBniCS#26]
It seems that RBniCS is trying to project a parameterized expression everywhere in the domain instead of on a specific boundary given by the user.

The core of the problem is here:
```
/usr/local/lib/python3.7/dist-packages/rbnics/backends/dolfin/wrapping/evaluate_expression.py in evaluate_expression(expression, function, replaced_expression)
    19         assign(function, replaced_expression)
    20     elif isinstance(expression, Operator):
--> 21         project(replaced_expression, function.function_space(), function=function)
    22     else:
    23         raise ValueError("Invalid expression")
```

**Comment by francesco-ballarin** [comment]
Closing this as not planned. Considering the limited amount of development in the last three years, and the effort this task would require, it is unlikely that this issue will ever get addressed. Further thoughts on this may be given if/when pull back is reimplemented in `ufl4rom`.
