### ISSUE TITLE
name ‘ReduceBasis’ is not defined

### ISSUE THREAD

**Issue by yc2647** [RBniCS/RBniCS#34]
Hi, I had trouble when I tried to implement my own code into `reduction method = ReduceBasis(Problem)` and it gives me error: **name ‘ReduceBasis’ is not defined.**

I downloaded the whole directory from your Github and add my file into the tutorial_thermal_block folder, but I am not able to run ReduceBasis(), whereas it is working on your tutorial file.

I install my Python through Anaconda, and my Python3 –version is **3.8.10**. And I am running the program on my Linux virtualbox, the OS is **Ubuntu 20.04.2 LTS**. 

Thanks in advance for any help!

**Comment by francesco-ballarin** [comment]
I am guessing that the name you are looking for is `ReducedBasis` ;)
