### ISSUE TITLE
tutorial_nonlinear_parabolic_exact not run

### ISSUE THREAD

**Issue by Quy97** [RBniCS/RBniCS#35]
reduction_method.offline() with IndexError: list index out of range

**Comment by francesco-ballarin** [comment]
Thanks @Quy97 for the bug report. Can you please copy the entire stack trace?

**Comment by Quy97** [comment]
Hi Sir,

When i run command   reduction_method.offline() in File
"tutorial_nonlinear_parabolic_exact.ipynb",
colab reported the following errors:
[image: image.png]

I not good at code, so i hope you can fix this bug for me.

Thanks you very much!

Regards,
Quy97

Vào Th 2, 25 thg 7, 2022 vào lúc 16:29 Francesco Ballarin <
***@***.***> đã viết:

**Comment by francesco-ballarin** [comment]
Hi, unfortunately github has stripped your image.

It would be best if you could copy the error text itself (you may want to use markdown to format it), so that we can copy e.g. the filename of the file which is giving the error.

**Comment by francesco-ballarin** [comment]
Runs for me on colab after 5a51874. Feel free to reopen if you still have errors on your end.
